# Generated by Django 5.1 on 2024-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('horror', 'Horror'), ('comedy', 'Comedy'), ('science-fiction', 'Science-Fiction'), ('adult', 'Adult'), ('thrilling', 'Thrilling'), ('romance', 'Romance')], max_length=60)),
                ('image', models.ImageField(upload_to='photos')),
                ('age_limit', models.CharField(max_length=10)),
            ],
        ),
    ]
