# Generated by Django 5.1 on 2024-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_movieid_alter_movie_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
