# Generated by Django 5.1 on 2024-09-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wishlist_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
