# Generated by Django 5.1 on 2024-09-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='qty',
        ),
    ]
