# Generated by Django 5.1 on 2024-09-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_subscription_qty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
