# Generated by Django 5.1 on 2024-09-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
